# run: conda env create --file environment.yml
name: fpw-dl
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python==3.7
  - anaconda
  - numpy>=1.14.5
  - opencv>=3.4.1
  - openpyxl>=3.0.0
  - scikit-image>=0.15.0,<0.16.0
  - cudatoolkit>=10.0.0,<10.1.0
  - cudnn>=7.6.0,<7.7.0
  - mahotas>=1.4.0,<1.5.0
  - pip:
    - tensorflow-gpu>=1.15.0,<1.16.0
    - keras>=2.2.4,<2.2.9
    - coloredlogs>=15.0.0
    - tqdm
    - seaborn