# run: conda env create --file environment.yml
name: fpw-dl
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - pip=21.3.*
  - numpy=1.18.5
  - openpyxl=3.0.*
  - scikit-image=0.15.*
  - cudatoolkit=10.0.*
  - cudnn=7.6.*
  - conda-forge::mahotas=1.4.*
  - opencv=3.4.*
  - pip:
    - tensorflow-gpu>=1.15.0,<1.15.6
    - keras==2.2.4
    - coloredlogs
    - tqdm
    - seaborn
    - requests
    - colorama
    - bs4
    - lxml
    - tinycss2>=1.0.0